# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SplendoSharedApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'KVOController'
  pod 'Bond', '~> 6.0'
  pod 'SharedLibrary', :path => './'
  pod 'J2ObjC-Framework', :git => 'https://github.com/Daeda88/J2ObjC-Framework.git', :branch => 'v1.2'

  target 'SplendoSharedAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SplendoSharedAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
